### PR TITLE
Cpu percent

### PR DESCRIPTION
**Pull request by Camerooooon**
`acs get usage`
This only adds the ability to get the CPU usage but it doesn't display it on a per core basis in acs monit. I will make that work later.

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Yay! Thanks!!

**Comment by Camerooooon** [comment]
See #270 and #271

**Comment by Camerooooon** [comment]
I also still need to write tests.

**Comment by Camerooooon** [comment]
This is all ready for merge by the way @JakeRoggenbuck

**Review by JakeRoggenbuck — APPROVED** [review]

**Pull request merged**
