### PR TITLE
Try auto tests

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by Shuzhengz** [comment]
That moment when the auto test feature fails build test

**Comment by JakeRoggenbuck** [comment]
Oof, you can also run 'cargo fmt' to check the formatter

**Comment by JakeRoggenbuck** [comment]
> 

Yea, basically tests only run on machines that have batteries and lids, trying to remove that.

**Comment by JakeRoggenbuck** [comment]
```

failures:
    system::tests::acs_check_available_governors_test
    system::tests::acs_check_cpu_freq_test
    system::tests::acs_check_turbo_enabled_test
    system::tests::acs_list_cpu_governors_test
    system::tests::acs_list_cpu_speeds_test
    system::tests::acs_list_cpu_temp_test
    system::tests::acs_list_cpus_test

test result: FAILED. 5 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

**Comment by JakeRoggenbuck** [comment]
```

failures:
    system::tests::acs_check_turbo_enabled_test
    system::tests::check_available_governors_test
    system::tests::check_cpu_freq_test
    system::tests::list_cpu_governors_test
    system::tests::list_cpu_speeds_test
    system::tests::list_cpu_temp_test
    system::tests::list_cpus_test

test result: FAILED. 8 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```

**Pull request merged**
