### PR TITLE
Fix Animation Postition

### PR DESCRIPTION
**Pull request by Shuzhengz**
Move it down one line because oops

### CODE REVIEW

**Comment by Shuzhengz** [comment]
wait we need to check if the window is in wide or floating

**Comment by JakeRoggenbuck** [comment]
We also have to check the size of the windows (width) because the first line can wrap and move it

**Comment by JakeRoggenbuck** [comment]
We may also want future stuff to be before the turbo so we need to make the location variable

**Comment by Shuzhengz** [comment]
yee

**Comment by Camerooooon** [comment]
When I run this code I get the animation looks like
```
Battery: 84%
  Turbo: yes
◷
```
Whilst normally it looks like:
```
Battery: 84%
◷ Turbo: yes

```
The second one is what I believe to be the intended behaviors.
So what is the purpose of this PR?

**Comment by Shuzhengz** [comment]
thats why its still a draft pr lol
im still working on fixing it

**Comment by Shuzhengz** [comment]
I also added a feature to keep track of terminal size

**Comment by JakeRoggenbuck** [comment]
Looks good! Will test tomorrow morning on laptop!

**Review by JakeRoggenbuck — APPROVED** [review]

**Pull request merged**
