### PR TITLE
Add the ability to get CPU frequency

### PR DESCRIPTION
**Pull request by Camerooooon**
Most code used from
https://docs.rs/sys-info/0.7.0/src/sys_info/lib.rs.html#367-406

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
This looks good! I played around with how to deal with the result from the file open, but I'm not exactly sure. I'll keep researching in the morning.

**Comment by JakeRoggenbuck** [comment]
I've looked into it more and I think I have a solution. We need to put the file read into a match with Ok and Err as the things it check for. The return type is correct. We now just need to have the Err return Err(Error::IO)

This would look like
```rs
match File::open(...) {
    Ok(_) => {
        ...
    },
    Err(_) => Err(Error::IO),
}

**Comment by Camerooooon** [comment]
> I've looked into it more and I think I have a solution. We need to put the file read into a match with Ok and Err as the things it check for. The return type is correct. We now just need to have the Err return Err(Error::IO)
> 
> This would look like
> 
> ```rust
> match File::open(...) {
>     Ok(_) => {
>         ...
>     },
>     Err(_) => Err(Error::IO),
> }
> ```

That's what the ? operator does on the line `File::open("/proc/cpuinfo")?.read_to_string(&mut cpu_info);`

**Comment by JakeRoggenbuck** [comment]
YOO, i forgot you can do that, aight, rust is a great language. Yea, if you add a `?` at the end of that line, then it works. Instead of the match stuff.

**Comment by Camerooooon** [comment]
> YOO, i forgot you can do that, aight, rust is a great language. Yea, if you add a `?` at the end of that line, then it works. Instead of the match stuff.

For some reason I couldn't get the ? operator to work in this case
```           
match get_cpu_freq() {
  Ok(f) => println!("CPU freq is {} MHz", f),
  Err(_) => println!("Failed")
}
```
Probably because the main function doesn't return a result.

**Pull request merged**
