### PR TITLE
Security & Refactor

### LINKED ISSUE #345: Create an Opt-In security updates warning.
In the config, the user will have to manually opt-in to security update warnings by setting this in the config.
```toml
security_update_warnings = true
```
If this is set, acs will in the background check the latest version of acs and will show whether it needs an update for security reasons.

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #345

### CODE REVIEW

**Comment by Camerooooon** [comment]
Why don't we just make it all updates. Like a message to tell the user ACS is out of date? It doesn't necessarily need to be security updates. Also we can use GitHub API to check releases on the acs page!

**Comment by JakeRoggenbuck** [comment]
Yea, I like the all updates idea, yea!

**Comment by JakeRoggenbuck** [comment]
and the github api will be very useful here

**Comment by Shuzhengz** [comment]
we should also prob update our dependencies sometimes

**Comment by JakeRoggenbuck** [comment]
> we should also prob update our dependencies sometimes

good idea, I'll do that

**Pull request closed without merging**
