### PR TITLE
Change Error to Option and add cached

### LINKED ISSUE #168: We check get_best_path() each time functions are called
These functions all call get_best_path every time they are called 
- read_power_source
- read_battery_charge
- read_lid_state

We should do something at the start to determine each path

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #168

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Needs test

**Review by Shuzhengz — APPROVED** [review]
although isn't cached already in another pr? might cause conflicts

**Comment by JakeRoggenbuck** [comment]
battery not found 
image

**Comment by JakeRoggenbuck** [comment]
image

**Pull request closed without merging**
