### PR TITLE
Interface interactive

### LINKED ISSUE #278: Make interactive mode for acs commands

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #278 and #277

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Interactive mode 
image

**Comment by JakeRoggenbuck** [comment]
image

**Review by Shuzhengz — APPROVED** [review]
I would actually simplify things to smth like `cpu1: 2500 MHz` etc, but tested and works

**Comment by JakeRoggenbuck** [comment]
> I would actually simplify things to smth like `cpu1: 2500 MHz` etc, but tested and works

Sounds good, I made an issue for it

**Comment by JakeRoggenbuck** [comment]
> > I would actually simplify things to smth like `cpu1: 2500 MHz` etc, but tested and works
> 
> Sounds good, I made an issue for it

#279

**Comment by Camerooooon** [comment]
Looks sick!

**Pull request merged**
