### PR TITLE
Add powersave on overheat rules

### PR DESCRIPTION
**Pull request by Camerooooon**
Right now I'm unsure if this logic is correct

### CODE REVIEW

**Comment by Camerooooon** [comment]
Wait for #222 to merge

**Comment by JakeRoggenbuck** [comment]
I can test in a bit

**Comment by JakeRoggenbuck** [comment]
Only one thing I would change, commit and should_graph were moved to settings.rs, so they can be removed from daemon_init and struct Daemon, but other than that, looks good!

**Comment by JakeRoggenbuck** [comment]
Smart getting get_highest temp, because sometimes one core might be like wayyyy higher and could get damaged without the system average being too hot. good job!

**Comment by JakeRoggenbuck** [comment]
> I'm also making temp threshold configurable.

Yees!!

**Comment by JakeRoggenbuck** [comment]
Make sure to add `overheat_threshold = 80` to [acs.toml](https://github.com/JakeRoggenbuck/auto-clock-speed/blob/main/acs.toml)

**Comment by JakeRoggenbuck** [comment]
Awesome, looks great!!

**Comment by JakeRoggenbuck** [comment]
I can test tomorrow morning

**Comment by JakeRoggenbuck** [comment]
fixes #122

**Comment by JakeRoggenbuck** [comment]
The logic looks solid. Great implementation. The only real way to test is to put a heater up to the laptop while opening a million tabs. I will try setting the threshold low, then put my laptop in the freezer, then move it into a space heater while building kernel from source. Wish me luck.

**Comment by JakeRoggenbuck** [comment]
image

**Comment by JakeRoggenbuck** [comment]
it works! 
image

**Comment by JakeRoggenbuck** [comment]
@Camerooooon good to merge?

**Review by JakeRoggenbuck — APPROVED** [review]

**Comment by Camerooooon** [comment]
Plugging it in after temp is overheating is going to cause problems. We don't want the governor to switch back to performance when you plug the laptop in.

**Comment by JakeRoggenbuck** [comment]
> Plugging it in after temp is overheating is going to cause problems. We don't want the governor to switch back to performance when you plug the laptop in.
Oh, true, hmm. Maybe we should give daemon a state. For example, normal, low_power, overheating, closed, etc.

**Comment by JakeRoggenbuck** [comment]
Sure, that would be good. I can make the state.rs and stuff, and then we could work together on adding state everywhere

**Pull request merged**
