### PR TITLE
Add flag to manually disable animation, systemctl

### LINKED ISSUE #151: Monit and run not shown in systemctl status or journal
**Describe the bug**
Monit and run not shown in systemctl status or journal
image

**To Reproduce**
1. Install current acs
2. Ran command 'systemctl restart acs'
3. See error

**Expected behavior**
It should show
image

**On Laptop**
Version: e3480ed

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #151 
- Fix systemctl issue of not updating and only displaying [10B blob data]

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
I love the turbo animation along with other animations but it looks like it breaks systemctl journal when it is running.

**Comment by JakeRoggenbuck** [comment]
This will be a way to turn it off just for systemctl but to keep it in monitor by default

**Comment by JakeRoggenbuck** [comment]
image

**Comment by JakeRoggenbuck** [comment]
We may also want to have a systemctl format flag to fix the tabs sometime later

**Review by Shuzhengz — APPROVED** [review]

**Pull request merged**
