### PR TITLE
Add ignore power and lid

### LINKED ISSUE #253: Option to ignore power
Running this software on a Raspberry Pi and i want the option to skip power check cause if i run it as a service it bumps it up to performance since it thinks it is a laptop so if there could be a param in  the config like 

ignore_power=yes

so it can focus on giving a low power raspberry pi the chance to go even lower in power consumption by powersaving and giving it power when its needed.

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #253

### CODE REVIEW

**Review by Camerooooon — COMMENTED** [review]
It works properly, maybe we should do a simpler implementation for the end user. Perhaps we could have a `enabled_rules` value on the config which contains a list of the currently active rules, (ex battery, lid, cpu_usage etc).

**Review by Shuzhengz — APPROVED** [review]
works on my laptop

**Comment by JakeRoggenbuck** [comment]
> 

I like this idea, yea

**Comment by JakeRoggenbuck** [comment]
I'll make a new issue for two things,
- A `list active rules` command
- A enable/disable rules in config.

**Comment by JakeRoggenbuck** [comment]
Yea, and also, that list of rules in the config could represent an actual list of function pointers that get called each cycle.

**Comment by JakeRoggenbuck** [comment]
We could probably do both the ignore_power + ignore_lid, and the select/deselect specific rules to allow easy toggle of rules or manual and controlled specific rules. This would also probably be really helpful for debugging.

**Comment by JakeRoggenbuck** [comment]
I'll probably merge this because it's a start, but I'll make an issue to add the extended version because it's a good idea.

**Pull request merged**
