### PR TITLE
Add the most basic show config

### LINKED ISSUE #207: Config viewer
`--print-config` to show config in use and it's parameters

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #207

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Needs test

**Comment by Shuzhengz** [comment]
wait which command does `--print-config` go with?

**Comment by JakeRoggenbuck** [comment]
I just changed it to a sub command of `showconfig`
```
acs showconfig
```

**Comment by Shuzhengz** [comment]
ooo ok

**Review by Shuzhengz — CHANGES_REQUESTED** [review]
works, but if it's using default config then its just going to error out instead of showing the default config

**Comment by JakeRoggenbuck** [comment]
Hm, yea. I can fix that

**Comment by Shuzhengz** [comment]
also the dependency package count went from 70 to 186 in this pr, need to test the peformance effects

**Comment by JakeRoggenbuck** [comment]
Yea, we can remove bat, because that is pretty intense

**Comment by JakeRoggenbuck** [comment]
Should be good to go now

**Review by Camerooooon — APPROVED** [review]
Works :)

**Comment by JakeRoggenbuck** [comment]
Thanks!

**Pull request merged**
