### PR TITLE
[RFC] First iteration of OOing Battery

### PR DESCRIPTION
**Pull request by blackduckx**
* Create a new Battery Class in power
* Setup most of the battery related functions to the class
* Fix a possible bugs in battery condition lookups
  My laptop does not have energy_full* sys controls
  but charge_full* sys controls

### CODE REVIEW

**Review by JakeRoggenbuck — COMMENTED** [review]
This looks great! I will be able to test this in a few hours. I can also see if I can get someone else to test in the mean time. Great work!

**Review by Camerooooon — APPROVED** [review]
Everything here is tested and looks amazing. I noticed some things that need to be further iterated which I listed in a new issue. It looks like these issues arose as a consequence of switching to an object-oriented model in addition to what was already present in our codebase. I listed what I noticed in #394 if you would like to take a look and maybe work on them.

Thank you so much for doing this, I believe switching the battery to object-oriented is a great way to improve the codebase.

**Review by JakeRoggenbuck — APPROVED** [review]
Very well done! Looks great.

**Comment by blackduckx** [comment]
Thank you guys for taking care of this chunk of code.
I had no luck to moving forward with this code this Week, but @Camerooooon & @JakeRoggenbuck you already did ;)

You definitly had the spirit ! One step forward, even not perfect. Thanks again.

**Pull request merged**
