### PR TITLE
Sort by cpu number

### LINKED ISSUE #205: Sorting is bad on CPUs over 10 cores
**Describe the bug**
Sorting breaks on CPUs with more than 10 cores

**To Reproduce**
1. Buy a CPU with more than 10 cores
2. Run acs monitor
3. The sorting will be thrown off

**Expected behavior**
see screenshot

**Screen
s
shots**

**On Laptop**
Version 0.1.7

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #205

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Needs test on large cpu @Shuzhengz

**Review by Shuzhengz — APPROVED** [review]
yup it works, but sorting in run is still broken

**Comment by JakeRoggenbuck** [comment]
It fixed monitor mode but not run?

**Comment by Shuzhengz** [comment]
yeah run is not sorted at all

**Comment by JakeRoggenbuck** [comment]
Weird, can you do `acs run -c`?

**Comment by JakeRoggenbuck** [comment]
Also, should we have like a debug mode for acs?

**Comment by JakeRoggenbuck** [comment]
> 

to check the commit because run sometimes does not update

**Comment by JakeRoggenbuck** [comment]
> > 
> 
> to check the commit because run sometimes does not update

**Comment by JakeRoggenbuck** [comment]
Oops, wrong button

**Comment by Shuzhengz** [comment]
ehhh
image

**Comment by JakeRoggenbuck** [comment]
I think that means that you are using an old version of acs

**Comment by JakeRoggenbuck** [comment]
if you install it with `cargo install --path .`, it should install the code currently checked out, and will show the commit hash at the bottom

**Comment by JakeRoggenbuck** [comment]
You could also do `cargo build` then run `sudo ./target/debug/acs run -c`

**Comment by Shuzhengz** [comment]
> I think that means that you are using an old version of acs

huh but that doesn't quite make sense
i did `cargo install --path` and it applied ur fix in monitor

**Comment by JakeRoggenbuck** [comment]
> 

Hm, weird. It's probably because the local acs is different from the global acs that root can access. Cargo install might only affect the local version? Something is causing root to not access it.

**Comment by Shuzhengz** [comment]
yea
that also might explain y i wasn't able to uninstall acs

**Comment by JakeRoggenbuck** [comment]
Ah, that would explain that

**Review by Shuzhengz — APPROVED** [review]

**Pull request merged**
