### PR TITLE
MSR Read

### LINKED ISSUE #41: Find a way to check power usage

### PR DESCRIPTION
**Pull request by Shuzhengz**
Reads information from the MSR registries
Also reads current CPU and GPU TDP if used correctly
Closes #41 #131

### CODE REVIEW

**Comment by Shuzhengz** [comment]
tiny problem
`use of unstable library feature 'asm': inline assembly is not stable enough for use and is subject to change`

**Comment by JakeRoggenbuck** [comment]
Thanks for going after this one!

**Comment by Shuzhengz** [comment]
yee

**Comment by Shuzhengz** [comment]
but yeah if we solve this asm problem we will be able to use it to read MSR, and we can get TDP, GPU TDP, clockspeed, max temp target, and potentially undervolting

**Comment by Shuzhengz** [comment]
@JakeRoggenbuck okay heres the big brain idea, what if we read from MSR in C, then export the values to rust

**Comment by JakeRoggenbuck** [comment]
> MSR

Yea! Does an MSR exist for rust? If not, we could make that library then use it as a dependency in case someone else needs MSR as well.

**Comment by JakeRoggenbuck** [comment]
This is a thing, not sure if it's the right thing, or the best thing https://docs.rs/x86_64/0.1.2/x86_64/registers/msr/index.html

We can always use our own if it's easier and more efficient

**Comment by Shuzhengz** [comment]
> This is a thing, not sure if it's the right thing, or the best thing https://docs.rs/x86_64/0.1.2/x86_64/registers/msr/index.html
> 
> 
> 
> We can always use our own if it's easier and more efficient

Yeah I tried to use that one, but the entire core::arch::asm is not available and the library doesn't build properly with our project

**Comment by Shuzhengz** [comment]
dat's why I said it might be a good idea to read it in c cuz intel actually gives the method to read from MSR in c

**Comment by Shuzhengz** [comment]
asm is still [not stablize](https://github.com/rust-lang/rust/issues/72016) enough to be used, [stablization PR not made](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr)

ill try using C/C++ and see if it works

**Comment by JakeRoggenbuck** [comment]
Great work with this! Looks super good

**Comment by JakeRoggenbuck** [comment]
This is going to be a great addition to acs

**Comment by Shuzhengz** [comment]
Thx!
I'm still trying to verify if the thing actually works tho, and I haven't integrated it with rust yet

**Comment by Shuzhengz** [comment]
The documentation on this is... well, intel didn't even bother to make a readme for it

**Comment by JakeRoggenbuck** [comment]
> The documentation on this is... well, intel didn't even bother to make a readme for it

Ooof, we might be able to help them out and write some docs for this, and then give it to them lol

**Comment by Shuzhengz** [comment]
well... yea...

image

**Comment by JakeRoggenbuck** [comment]
Lol, yea, that's a little while ago

**Comment by JakeRoggenbuck** [comment]
Seven years before GitHub was created

**Comment by Shuzhengz** [comment]
this code is older than anyone here lol

**Comment by Shuzhengz** [comment]
ayyy got reading msr in hex working in c
image

**Comment by Shuzhengz** [comment]
probably work on this a later time when we can use asm outside of experimental

**Pull request closed without merging**
