### PR TITLE
Refactor daemon

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
This needs to be tested well

**Comment by Shuzhengz** [comment]
ill test tmrw

**Comment by JakeRoggenbuck** [comment]
image

**Review by JakeRoggenbuck — COMMENTED** [review]
Tested on linux - dell

**Comment by JakeRoggenbuck** [comment]
Okay, we should start testing the daemon

**Comment by JakeRoggenbuck** [comment]
Like unit tests

**Pull request merged**
