### PR TITLE
Redo daemon logic

### PR DESCRIPTION
**Pull request by Camerooooon**
The daemon had some inconsistent logic and also didn't take into account edge cases (like starting the daemon while plugged in or plugging the laptop in while the lid was closed) Inorder to resolve I rewrote most the logic while still sticking to the main flowchart for making governor decisions.

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
I think this worked! I didn't test all edge case, compiled and seemed to work.

**Review by JakeRoggenbuck — APPROVED** [review]

**Comment by JakeRoggenbuck** [comment]
@Camerooooon Merge?

**Review by Shuzhengz — APPROVED** [review]
Works on mine

**Review by Shuzhengz — APPROVED** [review]
Have another approval

**Comment by Camerooooon** [comment]
Ready for merge then! (:

**Pull request merged**
