### PR TITLE
Fix error mgmt in config.rs

### PR DESCRIPTION
**Pull request by blackduckx**
Fix for 2 errors when building
error[E0277]: `std::io::ErrorKind` doesn't implement `std::fmt::Display`

Fix match to handle the error correctly

### CODE REVIEW

**Review by JakeRoggenbuck — APPROVED** [review]
Thanks!

**Comment by JakeRoggenbuck** [comment]
We use `cargo fmt` to format out code. You can just run `cargo fmt` and then commit&push, and i'll merge it. Thanks so much!

**Review by JakeRoggenbuck — APPROVED** [review]

**Comment by JakeRoggenbuck** [comment]
Thanks so much!

**Comment by blackduckx** [comment]
Hello,

Thx for the review. Code updated using cargo fmt (I'll update my IDE setup accordingly).

Regards,
Frédéric

**Comment by JakeRoggenbuck** [comment]
Awesome, thanks for the recent contributions! It means a lot!

**Comment by Camerooooon** [comment]
> Hello,
> 
> 
> 
> Thx for the review. Code updated using cargo fmt (I'll update my IDE setup accordingly).
> 
> 
> 
> Regards,
> 
> Frédéric
> 
> 

It's awesome to see new people contributing to ACS thank you so much for your PR!

**Pull request merged**
