### PR TITLE
Add set commands

### LINKED ISSUE #72: Add command to set gov
```
acs set gov performance
```

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #72

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
This will pose a large issue given that the should_change state is stored in an instance of Daemon and cannot be access from the outside.

**Comment by Camerooooon** [comment]
> This will pose a large issue given that the should_change state is stored in an instance of Daemon and cannot be access from the outside.

I think for now we should just let the cpu governor get overridden by the daemon and print out a warning to the user that it may be overridden and if they would like their choice to stay the same they should disable the service.

**Comment by JakeRoggenbuck** [comment]
Yea, it'll be hard to communicate from one instance of the program to another. We might have to make a state file or something. This might turn into a much bigger change of how the program works. It might be a good change going forward, making it easier to do similar things like this.

**Comment by Camerooooon** [comment]
I think we should just merge this since it's such a needed feature. We can work on a better way to make sure the governor doesn't get overridden later.

**Comment by JakeRoggenbuck** [comment]
Yea, I read your message again and I see what you mean, good idea! Lets merge it. I'll make an issue to "check if the daemon is already running when set command is run" that we can do later. Then I'll make an issue for finding another way to store state outside a single instance of daemon. Thanks

**Comment by JakeRoggenbuck** [comment]
We just need one last thing for it to work

**Comment by JakeRoggenbuck** [comment]
Okay, now it sets the gov when sudo is used but it does not show an error when sudo is not used.

**Comment by JakeRoggenbuck** [comment]
Okay, it should work? Can you test as well @Camerooooon

**Comment by JakeRoggenbuck** [comment]
Basically, you can do this
```
sudo acs set gov powersave
sudo acs set gov performance
```

```
# This will give an error about perms
acs set gov powersave
acs set gov performance
```

```
# These will give an error about gov name
set gov abcd
sudo set gov abcd
```

**Comment by JakeRoggenbuck** [comment]
All cases work on my machine

**Review by Camerooooon — APPROVED** [review]
Works!

**Pull request merged**
