### PR TITLE
Add all changed for csv enabled

### LINKED ISSUE #469: Don't call csv_write from start_loop if csv is not enabled

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #469

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
This is a huge speed up if csv is not enabled. This entire green block doesn't get called.
image


Better version of #467

**Comment by Camerooooon** [comment]
I have this fixed in https://github.com/JakeRoggenbuck/auto-clock-speed/pull/461. If we merge now it will cause conflicts. Sorry, I didn't realize yesterday.

**Comment by JakeRoggenbuck** [comment]
> I have this fixed in #461. If we merge now it will cause conflicts. Sorry, I didn't realize yesterday.

That's alright, I don't think it will cause because the area where we implement it only overlaps by a line but if you want to have the flag checked like this in your PR, that's alright by me.
 
We need to make sure that the flag gets checked before the function gets called.
```rs
if do_thing {
  thing();
}
```
and not something like this.
```rs
fn thing() {
  if !do_thing { return; }
}

thing();
```

The implementations are kinda different.

**Comment by JakeRoggenbuck** [comment]
Fixed in #461

**Pull request closed without merging**
