### PR TITLE
Change where get max and min get called

### LINKED ISSUE #99: cpu.update calls get_max and get_max
This is an issue, because max and min should not change, be they get updated often. They should be stored at init. This will also help fix #96 if it's added on to.

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #99

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
This will mean get_max will only call once at start.

**Comment by JakeRoggenbuck** [comment]
Wait, cpus max and min can change independently

**Comment by JakeRoggenbuck** [comment]
@Camerooooon @Shuzhengz Do we think that min and max cpu speed will change when this is running?

**Comment by Shuzhengz** [comment]
min will be 0 (cant have negative hz), and max will be the max boost clock for the specific cpu (unless they somehow manages to overclock their laptop cpu, in that case you need msr to read it)

**Comment by JakeRoggenbuck** [comment]
Cool, thanks

**Comment by JakeRoggenbuck** [comment]
I remember we were talking about having a setting to undo this change in case people had hot-swappable cpus but maybe it isn't something we need to super. Should we merge this? It just reduces the call of get_max and get_min from every tick to just once at the start

**Review by Shuzhengz — APPROVED** [review]
lgtm

**Pull request merged**
