### PR TITLE
Systemd

### PR DESCRIPTION
**Pull request by Camerooooon**
**Someone please try to follow my directions to setup systemd and acs before merging**

### CODE REVIEW

**Comment by Camerooooon** [comment]
Closes #50

**Comment by JakeRoggenbuck** [comment]
Very well done!

**Comment by JakeRoggenbuck** [comment]
It works on my machine, and auto starts on reboot

**Comment by JakeRoggenbuck** [comment]
Good to merge?

**Review by JakeRoggenbuck — APPROVED** [review]

**Pull request merged**
