### PR TITLE
Render most of `print` before clear

### LINKED ISSUE #188: Remove flickering of monit and run

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #188
This totally removes flickering of monitor and run

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
Tested!

**Comment by JakeRoggenbuck** [comment]
Can someone else please test

**Comment by Shuzhengz** [comment]
I dont have my laptop w me rn but i can test tonight

**Comment by JakeRoggenbuck** [comment]
Suggestion for concept art
ACS

**Comment by JakeRoggenbuck** [comment]
ACS rs

**Review by Shuzhengz — APPROVED** [review]
yup it works

**Comment by JakeRoggenbuck** [comment]
Yayy, thanks!

**Pull request merged**
