### PR TITLE
Add docker check

### LINKED ISSUE #430: Containers and VMs
Sometimes if the program is running inside a container or VM it cannot see the turbo speed, only the base speed. We should probably tell the user that they’re using the program inside a container so the speed may not be accurate.

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #430

### CODE REVIEW

**Comment by JakeRoggenbuck** [comment]
This only shows when in docker 

image

**Review by Camerooooon — APPROVED** [review]
Looks great.

**Comment by Shuzhengz** [comment]
mate sleep is a thing yk
"y'all gotta stop pulling all-nighters" -- Linus Torvalds 2022 (yes he did actually say that)

**Comment by JakeRoggenbuck** [comment]
lmaoo, i did not even notice it was 1:39AM

**Pull request merged**
