### PR TITLE
Check lid state when daemon initializes

### LINKED ISSUE #71: Lid sometimes takes one time to open and close before it reacts
ACS is supposed to set gov to powersave when the lid closes. This does happen but sometimes it takes one open/close before it works. This might have to do with the initial state of the lid set in daemon.rs.

### PR DESCRIPTION
**Pull request by JakeRoggenbuck**
fixes #71

### CODE REVIEW

**Review by Camerooooon — CHANGES_REQUESTED** [review]
Can you also add a check for when the lid is opened again to turn performance back on if plugged in

**Comment by JakeRoggenbuck** [comment]
Good idea! I'll make an issue for that.

**Comment by JakeRoggenbuck** [comment]
Added #92

**Comment by JakeRoggenbuck** [comment]
Works!

**Pull request merged**
