### PR TITLE
Activated rules config values

### LINKED ISSUE #295: Add enabled_rules to config for daemon rule selection
As suggested by Cameron in a comment in PR #291, we should allow the user to add names of rules to a enabled_rules list that will only run those rules so the end user has more ability to customize.

Original comment: https://github.com/JakeRoggenbuck/auto-clock-speed/pull/291#pullrequestreview-988654392

### PR DESCRIPTION
**Pull request by Camerooooon**
Closes #295

### CODE REVIEW

**Comment by Camerooooon** [comment]
I haven't tested disabling all the rules yet since I don't have access to my charger and stuff right now.

**Comment by Camerooooon** [comment]
Also closes #296

**Comment by Camerooooon** [comment]
Because the old version of this code didn't actually modify rules I propose we release a v0.1.9b version so that we can get the rule stuff working in the latest release.

**Comment by JakeRoggenbuck** [comment]
> Because the old version of this code didn't actually modify rules I propose we release a v0.1.9b version so that we can get the rule stuff working in the latest release.

I agree, yea. I'll test right after I get home

**Comment by JakeRoggenbuck** [comment]
Great work, and happy last few days of school

**Review by JakeRoggenbuck — APPROVED** [review]
Awesome!

**Pull request merged**
